export const queryKeys = {
  session: ['session'] as const,
  profile: ['profile'] as const,
  onboarding: ['onboarding', 'me'] as const,
  bodyMeasurements: ['body-measurements', 'me'] as const,
  equipment: ['equipment'] as const,
  exercises: (filters: string) => ['exercises', filters] as const,
  favorites: ['favorites'] as const,
  workouts: (page: number) => ['workouts', page] as const,
  workout: (id: string) => ['workout', id] as const,
  routines: (scope: string) => ['routines', scope] as const,
  routine: (id: string) => ['routine', id] as const,
  routineAssignments: ['routines', 'assignments', 'me'] as const,
  coachAssignments: ['routines', 'assignments', 'coach'] as const,
  membership: ['membership', 'me'] as const,
  membershipAccesses: ['membership', 'accesses'] as const,
  membershipOptions: ['membership', 'options'] as const,
  accessHistory: (page: number) => ['access', 'me', page] as const,
  credentials: ['credentials', 'me'] as const,
  notifications: (page: number) => ['notifications', page] as const,
  notificationPreference: ['notifications', 'preference'] as const,
  tutorialProgress: ['tutorials', 'progress', 'me'] as const,
  admin: {
    branches: (page: number) => ['admin', 'branches', page] as const,
    rooms: (page: number) => ['admin', 'rooms', page] as const,
    maintenance: (page: number) => ['admin', 'maintenance', page] as const,
    plans: ['admin', 'plans'] as const,
    media: ['admin', 'media'] as const,
    staff: (page: number, position: string) => ['admin', 'staff', page, position] as const,
    customers: (page: number) => ['admin', 'customers', page] as const,
    memberships: (page: number) => ['admin', 'memberships', page] as const,
    accessDevices: ['admin', 'access-devices'] as const,
    accessHistory: (page: number) => ['admin', 'access-history', page] as const,
  },
};
